name: chatv28
description: ChatV28.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # C
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2

  # F
  firebase_auth: ^3.3.3
  flutter_local_notifications: ^9.1.5
  firebase_core: ^1.10.5
  flutter_spinkit: ^5.1.0
  file_picker: ^4.2.7
  firebase_analytics: ^9.0.3
  firebase_storage: ^10.2.3
  firebase_messaging: ^11.2.4
  flutter_keyboard_visibility: ^5.1.0
  
  # G
  get_it: ^7.2.0
  grouped_list: ^4.1.0

  # I
  ionicons: ^0.1.2

  # P
  provider: ^6.0.1
  
  # T
  timeago: ^3.1.0

  # S
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

 