name: chatv28
description: ChatV28.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  

dependencies:
  flutter:
    sdk: flutter

  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git
      ref: master

  flutter_absolute_path: 
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git

  # A
  awesome_notifications: ^0.6.20

  # C
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  crypto: ^3.0.1
  chips_choice_null_safety: ^2.0.4
  carousel_slider: ^4.0.0
  circular_countdown_timer: ^0.2.0

  # D
  dio: ^4.0.4

  # F
  flutter_screenutil: ^5.0.2
  firebase_auth: ^3.3.3
  flutter_local_notifications: ^9.1.5
  firebase_core: ^1.10.5
  flutter_native_timezone: ^2.0.0
  flutter_spinkit: ^5.1.0
  file_picker: ^4.2.7
  firebase_analytics: ^9.0.3
  firebase_storage: ^10.2.3
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: ^11.2.4
  
  # G
  get_it: ^7.2.0
  geocoding: ^2.0.2
  google_maps_flutter: ^2.1.1
  google_maps_place_picker_mb: ^2.0.0-mb.9
  geolocator: ^8.0.3
  grouped_list: ^4.1.0

  # I
  image_cropper: ^1.4.1
  ionicons: ^0.1.2

  # H
  http: ^0.13.4

  # K
  keyboard_dismisser: ^2.0.0

  # P
  provider: ^6.0.1
  photo_view: ^0.13.0
  popover: ^0.2.6+3

  # R
  rxdart: ^0.27.3
  
  # T
  timeago: ^3.1.0

  # S
  shared_preferences: ^2.0.11
  soundpool: ^2.2.0
  stream_transform: ^2.0.0

  # U
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-chatify.png"

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/
    

  fonts:
    - family: Dongle
      fonts: 
      - asset: assets/fonts/dongle/Dongle-Regular.ttf
      - asset: assets/fonts/dongle/Dongle-Light.ttf
      - asset: assets/fonts/dongle/Dongle-Bold.ttf
 